/*Config
    Retorno
        -DadosPessoaisEntidade
    Parametros
        -CD_PESSOA:int
*/

SELECT 
    FI_PESSOA_FISICA.IR_SEXO, 
    FI_PESSOA_FISICA.DT_NASCIMENTO, 
    FI_PESSOA_FISICA.NR_CPF,
	CASE
		WHEN FI_PESSOA_FISICA.IR_SEXO = 'M' THEN 'MASCULINO'
		WHEN FI_PESSOA_FISICA.IR_SEXO = 'F' THEN 'FEMININO'
	END AS DS_SEXO
FROM FI_PESSOA_FISICA
INNER JOIN FI_PESSOA ON FI_PESSOA.CD_PESSOA = FI_PESSOA_FISICA.CD_PESSOA
WHERE FI_PESSOA.CD_PESSOA = @CD_PESSOA