CREATE TABLE WEB_CALENDARIO_PGT (
   OID_CALENDARIO_PGT   NUMERIC(10)          IDENTITY,
   DES_MES              VARCHAR(50)          NOT NULL,
   NUM_DIA              NUMERIC(10)          NOT NULL,
   CD_PLANO             VARCHAR(4)           NULL,
   CONSTRAINT WEB_CALENDARIO_PGT_PK PRIMARY KEY (OID_CALENDARIO_PGT)
)
go

DELETE FROM WEB_CALENDARIO_PGT;

--plano 1
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Janeiro', 31, '1');
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Fevereiro',28, '1' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Março',31, '1' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Abril',30, '1' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Maio',29 , '1');
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Junho',30, '1' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Julho', 31, '1');
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Agosto',31, '1' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Setembro', 30, '1');
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Outubro',30, '1' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Novembro',27, '1' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Abono Anual',18, '1' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Dezembro', 30, '1');

--plano 2
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Janeiro', 31, '2');
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Fevereiro',28, '2' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Março',31, '2' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Abril',30, '2' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Maio',29 , '2');
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Junho',30, '2' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Julho', 31, '2');
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Agosto',31, '2' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Setembro', 30, '2');
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Outubro',30, '2' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Novembro',27, '2' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Abono Anual',18, '2' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Dezembro', 30, '2');

--plano 3
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Janeiro', 31, '3');
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Fevereiro',28, '3' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Março',31, '3' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Abril',30, '3' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Maio',29 , '3');
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Junho',30, '3' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Julho', 31, '3');
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Agosto',31, '3' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Setembro', 30, '3');
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Outubro',30, '3' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Novembro',27, '3' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Abono Anual',18, '3' );
INSERT INTO WEB_CALENDARIO_PGT (DES_MES, NUM_DIA, CD_PLANO) VALUES ('Dezembro', 30, '3');