/*Config
    RetornaLista
    Retorno
        -SaldoEntidade
    Parametros
        -DT_REFERENCIA:DateTime
        -SQ_PLANO_PREVIDENCIAL:int
        -CD_PESSOA:int
*/

SELECT FI_FICHA_CONTRIB_PREVIDENCIAL.QT_COTA_CONTRIBUICAO, 
       FI_REGRA_RESGATE_INTERVALO.VL_RESGATE
  FROM FI_FICHA_CONTRIB_PREVIDENCIAL
INNER JOIN FI_CONTRATO_TRABALHO ON FI_CONTRATO_TRABALHO.SQ_CONTRATO_TRABALHO = FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_CONTRATO_TRABALHO
INNER JOIN FI_FUNDO_CONTRIBUICAO ON (FI_FUNDO_CONTRIBUICAO.SQ_TIPO_FUNDO = FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_TIPO_FUNDO) 
                                AND (FI_FUNDO_CONTRIBUICAO.SQ_PLANO_PREVIDENCIAL = FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_PLANO_PREVIDENCIAL)
INNER JOIN FI_REGRA_RESGATE ON FI_REGRA_RESGATE.SQ_REGRA_RESGATE = FI_FUNDO_CONTRIBUICAO.SQ_REGRA_RESGATE
INNER JOIN FI_REGRA_RESGATE_INTERVALO ON FI_REGRA_RESGATE_INTERVALO.SQ_REGRA_RESGATE = FI_FUNDO_CONTRIBUICAO.SQ_REGRA_RESGATE
WHERE (FI_FICHA_CONTRIB_PREVIDENCIAL.DT_REFERENCIA <= @DT_REFERENCIA) 
  AND (FI_FUNDO_CONTRIBUICAO.EE_SALDO_EXTRATO = 'S') 
  AND (FI_FUNDO_CONTRIBUICAO.IR_COLUNA = 'E') 
  AND (FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_PLANO_PREVIDENCIAL = @SQ_PLANO_PREVIDENCIAL) 
  AND (FI_CONTRATO_TRABALHO.CD_PESSOA = @CD_PESSOA) 
  AND (30 BETWEEN FI_REGRA_RESGATE_INTERVALO.QT_TEMPO_MINIMO AND FI_REGRA_RESGATE_INTERVALO.QT_TEMPO_MAXIMO)