/*Config
    Retorno
        -SaldoEntidade
    Parametros
        -DT_REFERENCIA:DateTime
        -SQ_PLANO_PREVIDENCIAL:int
        -CD_PESSOA:int
        -IR_TIPO:string
*/

SELECT
  SUM(FI_FICHA_CONTRIB_PREVIDENCIAL.QT_COTA_CONTRIBUICAO) AS QT_COTA_CONTRIBUICAO,
  SUM(FI_FICHA_CONTRIB_PREVIDENCIAL.VL_CONTRIBUICAO) AS VL_CONTRIBUICAO
FROM FI_FICHA_CONTRIB_PREVIDENCIAL
INNER JOIN FI_CONTRATO_TRABALHO ON FI_CONTRATO_TRABALHO.SQ_CONTRATO_TRABALHO = FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_CONTRATO_TRABALHO
INNER JOIN FI_FUNDO_CONTRIBUICAO ON FI_FUNDO_CONTRIBUICAO.SQ_TIPO_FUNDO = FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_TIPO_FUNDO
INNER JOIN FI_TIPO_COBRANCA ON FI_TIPO_COBRANCA.SQ_TIPO_COBRANCA = FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_TIPO_COBRANCA
WHERE (FI_FICHA_CONTRIB_PREVIDENCIAL.DT_REFERENCIA <= @DT_REFERENCIA) 
  AND (FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_PLANO_PREVIDENCIAL = @SQ_PLANO_PREVIDENCIAL) 
  AND (FI_FUNDO_CONTRIBUICAO.IR_COLUNA = @IR_TIPO) 
  AND (FI_CONTRATO_TRABALHO.CD_PESSOA = @CD_PESSOA)
  AND (FI_TIPO_COBRANCA.IC_CATEG_CONTRIBUICAO <> 'R')