/*Config
    RetornaLista
    Retorno
        -ContrachequeEntidade
    Parametros
        -SQ_CONTRATO_TRABALHO:int
        -SQ_PLANO_PREVIDENCIAL:int
*/

SELECT DISTINCT 
	CRONO.DT_REFERENCIA,
    CRONO.SQ_CRONOGRAMA
FROM FI_FICHA_FINANC_ASSISTIDO FF
INNER JOIN FI_PROCESSO_BENEFICIO PB ON PB.SQ_PROCESSO = FF.SQ_PROCESSO
INNER JOIN FI_CRONOGRAMA_CREDITO CRONO ON CRONO.SQ_CRONOGRAMA = FF.SQ_CRONOGRAMA
WHERE PB.SQ_CONTRATO_TRABALHO = @SQ_CONTRATO_TRABALHO
  AND PB.SQ_PLANO_PREVIDENCIAL = @SQ_PLANO_PREVIDENCIAL
  AND CRONO.DT_FECHAMENTO IS NOT NULL
ORDER BY CRONO.DT_REFERENCIA DESC