#region Usings
using Dapper;
using Intech.Lib.Dapper;
using Intech.Lib.Web;
using Intech.Advanced.Entidades;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
#endregion

namespace Intech.Advanced.Dados.DAO
{   
    public abstract class ContribuicaoDAO : BaseDAO<ContribuicaoEntidade>
    {
        
		public virtual IEnumerable<ContribuicaoEntidade> BuscarPorPlanoContratoTrabalho(int SQ_CONTRATO_TRABALHO, int SQ_PLANO_PREVIDENCIAL)
		{
			if(AppSettings.IS_SQL_SERVER_PROVIDER)
				return Conexao.Query<ContribuicaoEntidade>("SELECT  	FI_FICHA_CONTRIB_PREVIDENCIAL.*,     FI_FUNDO_CONTRIBUICAO.DS_TIPO_FUNDO, 	FI_TIPO_COBRANCA.DS_TIPO_COBRANCA FROM FI_FICHA_CONTRIB_PREVIDENCIAL  INNER JOIN FI_FUNDO_CONTRIBUICAO ON FI_FUNDO_CONTRIBUICAO.SQ_TIPO_FUNDO = FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_TIPO_FUNDO INNER JOIN FI_TIPO_COBRANCA ON FI_TIPO_COBRANCA.SQ_TIPO_COBRANCA = FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_TIPO_COBRANCA WHERE FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_CONTRATO_TRABALHO = @SQ_CONTRATO_TRABALHO   AND FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_PLANO_PREVIDENCIAL = @SQ_PLANO_PREVIDENCIAL   AND FI_FICHA_CONTRIB_PREVIDENCIAL.DT_REFERENCIA = (SELECT MAX(DT_REFERENCIA)  													 FROM FI_FICHA_CONTRIB_PREVIDENCIAL  													 WHERE SQ_CONTRATO_TRABALHO = @SQ_CONTRATO_TRABALHO  													   AND SQ_PLANO_PREVIDENCIAL = @SQ_PLANO_PREVIDENCIAL) ORDER BY DT_REFERENCIA DESC", new { SQ_CONTRATO_TRABALHO, SQ_PLANO_PREVIDENCIAL });
			else if(AppSettings.IS_ORACLE_PROVIDER)
				return Conexao.Query<ContribuicaoEntidade>("SELECT FI_FICHA_CONTRIB_PREVIDENCIAL.*, FI_FUNDO_CONTRIBUICAO.DS_TIPO_FUNDO, FI_TIPO_COBRANCA.DS_TIPO_COBRANCA FROM FI_FICHA_CONTRIB_PREVIDENCIAL INNER  JOIN FI_FUNDO_CONTRIBUICAO  ON FI_FUNDO_CONTRIBUICAO.SQ_TIPO_FUNDO=FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_TIPO_FUNDO INNER  JOIN FI_TIPO_COBRANCA  ON FI_TIPO_COBRANCA.SQ_TIPO_COBRANCA=FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_TIPO_COBRANCA WHERE FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_CONTRATO_TRABALHO=:SQ_CONTRATO_TRABALHO AND FI_FICHA_CONTRIB_PREVIDENCIAL.SQ_PLANO_PREVIDENCIAL=:SQ_PLANO_PREVIDENCIAL AND FI_FICHA_CONTRIB_PREVIDENCIAL.DT_REFERENCIA=(SELECT MAX(DT_REFERENCIA) FROM FI_FICHA_CONTRIB_PREVIDENCIAL WHERE SQ_CONTRATO_TRABALHO=:SQ_CONTRATO_TRABALHO AND SQ_PLANO_PREVIDENCIAL=:SQ_PLANO_PREVIDENCIAL) ORDER BY DT_REFERENCIA DESC", new { SQ_CONTRATO_TRABALHO, SQ_PLANO_PREVIDENCIAL });
			else
				throw new Exception("Provider não suportado!");
		}
    }
}
