/*Config
    RetornaLista
    Retorno
        -ContratoTrabalhoEntidade
    Parametros
        -CPF:string
*/

SELECT * 
FROM FI_CONTRATO_TRABALHO CONTRATO
INNER JOIN FI_PESSOA_FISICA ON FI_PESSOA_FISICA.CD_PESSOA = CONTRATO.CD_PESSOA
INNER JOIN FI_PLANO_VINCULADO AS PLANO ON PLANO.SQ_CONTRATO_TRABALHO = CONTRATO.SQ_CONTRATO_TRABALHO
WHERE FI_PESSOA_FISICA.NR_CPF = @CPF
  AND PLANO.SQ_SIT_PLANO NOT IN (2, 6, 7)