/*Config
    RetornaLista
    Retorno
        -ContratoTrabalhoEntidade
    Parametros
        -CPF:string
*/

SELECT CT.*,
	EMPRESA.NO_PESSOA AS NO_EMPRESA
FROM FI_CONTRATO_TRABALHO CT
INNER JOIN FI_PESSOA_FISICA PF ON PF.CD_PESSOA = CT.CD_PESSOA
INNER JOIN FI_PESSOA EMPRESA ON EMPRESA.CD_PESSOA = CT.CD_PESSOA_PATR
INNER JOIN FI_PLANO_VINCULADO AS PLANO ON PLANO.SQ_CONTRATO_TRABALHO = CT.SQ_CONTRATO_TRABALHO
WHERE PF.NR_CPF = @CPF
  AND PLANO.SQ_SIT_PLANO NOT IN (2, 6, 7)