/*Config
    Retorno
        -SalarioContribuicaoEntidade
    Parametros
        -SQ_CONTRATO_TRABALHO:int
        -SQ_PLANO_PREVIDENCIAL:int
        -DT_REFERENCIA:DateTime
*/

SELECT * FROM FI_FICHA_SALARIO_CONTRIBUICAO
WHERE SQ_CONTRATO_TRABALHO = @SQ_CONTRATO_TRABALHO
  AND SQ_PLANO_PREVIDENCIAL = @SQ_PLANO_PREVIDENCIAL
  AND DT_REFERENCIA = @DT_REFERENCIA