/*Config
    Retorno
        -HistValoresProcessoEntidade
    Parametros
        -CPF:string
        -SQ_PLANO_PREVIDENCIAL:int
*/

SELECT HP.*
FROM FI_HIST_VALORES_PROCESSO HP 
    INNER JOIN FI_PROCESSO_BENEFICIO PB ON HP.SQ_PROCESSO = PB.SQ_PROCESSO
    INNER JOIN FI_CONTRATO_TRABALHO CT ON CT.SQ_CONTRATO_TRABALHO = PB.SQ_CONTRATO_TRABALHO
    INNER JOIN FI_PESSOA_FISICA PF ON PF.CD_PESSOA = CT.CD_PESSOA
WHERE PF.NR_CPF = @CPF
  AND PB.SQ_PLANO_PREVIDENCIAL = @SQ_PLANO_PREVIDENCIAL
  AND HP.DT_INIC_VALIDADE = (SELECT MAX(HP2.DT_INIC_VALIDADE)
                               FROM FI_HIST_VALORES_PROCESSO HP2
                              WHERE HP2.SQ_PROCESSO = PB.SQ_PROCESSO)