/*Config
    Retorno
        -HistManutContribuicaoEntidade
    Parametros
        -SQ_CONTRATO_TRABALHO:int
*/

SELECT TOP 1 *
FROM FI_HIST_MANUT_CONTRIBUICAO
WHERE SQ_CONTRATO_TRABALHO = @SQ_CONTRATO_TRABALHO
  AND SQ_REGRA = 3
  AND SQ_PLANO_PREVIDENCIAL = 3
ORDER BY DT_INIC_VALIDADE DESC